### PR TITLE
test with mocha instead of jasmine

### PR DESCRIPTION
**Pull request by minrk**
maybe the multiple runs is what confuses codecov

Let's wait for the codecov report before merging, in case this doesn't change anything.

### CODE REVIEW

**Comment by minrk** [comment]
Nope, that wasn't it. Trying another thing...

**Comment by minrk** [comment]
still no. Trying a different test runner, perhaps.

**Comment by minrk** [comment]
@rgbkrk this doesn't fix the codecov issue, but do you have a preference for mocha vs jasmine (or another test runner)? You have a lot more js experience than I do at this point.

**Comment by minrk** [comment]
Switching to nyc with lcov reports seems to fix the issue.

**Comment by minrk** [comment]
#61 just does the nyc switch fixing codecoov, so this PR is now switching the runner to mocha. I'm not sure if I want to do that or not, but the work is done, and I'll leave it here.

**Comment by rgbkrk** [comment]
I tend to use `mocha` though I'm not really opinionated there. I've adapted for jasmine and tape as well.

**Comment by minrk** [comment]
Leaving this with jasmine for now. I don't see an advantage to mocha, but we can pick this up as a starting point if that changes.

**Pull request closed without merging**
