### PR TITLE
[wip] ensure optionally-decoded characters (@, ~) are treated the same as their encoded counterparts

### PR DESCRIPTION
**Pull request by minrk**
we already had it working one direction (%40->@), but not the other (@->%40)

related to jupyterhub/jupyterhub#1717 but not actually necessary for the fix

### CODE REVIEW

**Comment by minrk** [comment]
marking WIP since there seems to be something wonky

**Comment by Pugio** [comment]
Is there something blocking this? I have an issue with `%40` in usernames (`/user/myname@mydomain/` vs `/user/myname%40mydomain/`) returning 404s, which I think this PR would fix.

While my issue is with using `code-server` behind the jupyter-server-proxy, it is functionally identical to the problem discussed in jupyterhub/jupyterhub#2547.

**Comment by manics** [comment]
Please see the discussion on https://github.com/jupyterhub/jupyterhub/pull/3167. This is tricky to get right.

**Review by MTTrackNotion77 — APPROVED** [review]

**Comment by yuvipanda** [comment]
Given that @minrk has closed https://github.com/jupyterhub/jupyterhub/pull/3167, I'm going to close this PR as well. Feel free to re-open if you disagree, @minrk.

**Pull request closed without merging**
