### PR TITLE
Ability to query while extracting a specific data entry

### PR DESCRIPTION
**Pull request by stefanoborini**
Filters the results according to the passed query parameters. With /api/routes/?foo=bar it will extract only those entries whose data contains foo=bar

### CODE REVIEW

**Comment by willingc** [comment]
@minrk Is this something that can be merged or is there additional work needed?

**Comment by stefanoborini** [comment]
@willingc It was my understanding that it was not really needed (one could use alternative strategies), but I left the PR open in case it was topic of discussion

**Comment by willingc** [comment]
Thanks for the perspective @stefanoborini. Should I close the PR and label it as Reference for the benefit of others in the future?

**Comment by stefanoborini** [comment]
As far as I am concerned, it can be closed.

**Comment by willingc** [comment]
Closing this and marking it as reference.

Thank you @stefanoborini for the PR and your ongoing insights and support on JupyterHub. :cake:

**Pull request closed without merging**
